name = "fernandaepedro"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-01-08"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[[routes]]
pattern = "fernandaepedro.com"
custom_domain = true

[[routes]]
pattern = "www.fernandaepedro.com"
custom_domain = true
